spring:
  datasource:
    url: jdbc:mysql://ts-dev-mysql.aegis-info.com:3308/jl_leader_cloud?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 521215
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:kingbase8://localhost:54321/demo?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: SYSTEM
#    password: 521215
#    driver-class-name: com.kingbase8.Driver
#  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.Kingbase8Dialect
#    hibernate.ddl-auto: none
#    show-sql: false